# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simplifique
email: tiagoamaralc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog para compartilhamento de experiências pessoais no mundo da
  Tecnologia da Informação e outros assuntos que possam ser valiosos
  para a comunidade.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://actiago.github.io" # the base hostname & protocol for your site
twitter_username: actbot3
github_username:  actiago

# Build settings
markdown: kramdown
