url: 'https://blog.tiag0.com.br'
title: Blog | Tiago Amaral
author:
  name: Tiago Amaral
  email: actiago@duck.com
search: true
description: Bloco de notas rápidas para consulta e outras cositas más.

lang: "pt-BR"
timezone: "America/Sao_Paulo"

# Build settings
markdown: kramdown

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/

exclude:
  - Containerfile
  - README.md
  - script/
  - sitemap.xml
  - feed.xml
  - LICENSE
