title: Tiago Amaral
url: 'http://blog.tiag0.com.br/'

# email: me@tiag0.com.br
description: > # this means to ignore newlines until "baseurl:"
  Blog pessoal onde compartilho e salvo conteúdo de uso diário.

tagline: Sysadmin
pic: favicon.png
# baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username:
github_username: actiago
telegram: tcego

# Build settings
markdown: kramdown
