url: 'https://blog.tiag0.com.br'
title: Blog | Tiago Amaral
author: actiago
search: true
description: Bloco de notas rápidas para consulta e outras cositas más.

lang: "pt-BR"
timezone: "America/Sao_Paulo"

# social links
github_username: actiago
rss: rss
linkedin_username: ac-tiago

show_excerpts: false

# Minima date format
minima:
  date_format: "%b %-d, %Y"

# Build settings
# theme: minima  # removido — agora usamos layout próprio

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude assets from being processed by Jekyll
exclude:
  - Containerfile
  - README.md
  - script/
